### ISSUE TITLE
Sitecore.SharedSource.Logger is missing in the release package

### ISSUE THREAD

**Issue by MyriamDS** [NetlabSharedSource/SitecoreDataSync#1]
I've installed the available release package, but when running a data sync the module complains on not finding the Sitecore.SharedSource.Logger. When checking the bin-directory I do not see any Sitecore.SharedSource.Logger.dll neither.
I was looking forward on using this module so please advice.
Best regards,
Myriam

**Comment by kasperpagels** [comment]
?Hi Myriam

Thanks for Your email.

I can see that you are right, it is not included. Somehow TDS is not including related Projects, I have to check With Hedgehog on that.

But I've included a New package, you can install over the existing one. It should include the logger Assembly.

We use this module a lot, and With great results, so hope you also find it usefull.

With regards

Kasper Pagels
Prosjektleder og utvikler
Netlab AS
Mob: 45230001

---

Fra: MyriamDS notifications@github.com
Sendt: 13. januar 2015 16:26
Til: NetlabSharedSource/SitecoreDataSync
Emne: [SitecoreDataSync] Sitecore.SharedSource.Logger is missing in the release package (#1)

I've installed the available release package, but when running a data sync the module complains on not finding the Sitecore.SharedSource.Logger. When checking the bin-directory I do not see any Sitecore.SharedSource.Logger.dll neither.
I was looking forward on using this module so please advice.
Best regards,
Myriam

##

**Comment by MyriamDS** [comment]
Thanks. I'm looking forward to using it.
regards, Myriam
